// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://fmleplqssxndaynmxhjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtbGVwbHFzc3huZGF5bm14aGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjEzNTEsImV4cCI6MjA5MDAzNzM1MX0.pNIo5AR3w1spZJmNT_FI1OWLacRZfX9akSELG5YByGU";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Supabase configuration is missing. " +
    "Please configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your deployment environment."
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://fmleplqssxndaynmxhjr.supabase.co", // Fallback project URL to prevent crash
  SUPABASE_PUBLISHABLE_KEY || "placeholder",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);