// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://hcbsbgjlkqugwlkilinq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjYnNiZ2psa3F1Z3dsa2lsaW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3NjUxMTIsImV4cCI6MjA5NjM0MTExMn0.3FVKy1EPRKeVt3poEKZsV-x5xgFIp5oT37Nzaue737I";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Supabase configuration is missing. " +
    "Please configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your deployment environment."
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://hcbsbgjlkqugwlkilinq.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "placeholder",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);